# Generated by Django 5.0.2 on 2024-02-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed_by_task_created_at_task_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='selected_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
